// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: pluginsdk/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostBrokerId  uint32                 `protobuf:"varint,1,opt,name=host_broker_id,json=hostBrokerId,proto3" json:"host_broker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeRequest) GetHostBrokerId() uint32 {
	if x != nil {
		return x.HostBrokerId
	}
	return 0
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Metadata) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Metadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Cloud         string                 `protobuf:"bytes,2,opt,name=cloud,proto3" json:"cloud,omitempty"`
	CloudsPath    string                 `protobuf:"bytes,3,opt,name=clouds_path,json=cloudsPath,proto3" json:"clouds_path,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Context) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Context) GetCloud() string {
	if x != nil {
		return x.Cloud
	}
	return ""
}

func (x *Context) GetCloudsPath() string {
	if x != nil {
		return x.CloudsPath
	}
	return ""
}

func (x *Context) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Resources) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Aliases       []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Columns       []*Column              `protobuf:"bytes,5,rep,name=columns,proto3" json:"columns,omitempty"`
	Commands      []*Command             `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Resource) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Resource) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Resource) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Resource) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MinWidth      int32                  `protobuf:"varint,3,opt,name=min_width,json=minWidth,proto3" json:"min_width,omitempty"`
	Flex          int32                  `protobuf:"varint,4,opt,name=flex,proto3" json:"flex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Column) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Column) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Column) GetMinWidth() int32 {
	if x != nil {
		return x.MinWidth
	}
	return 0
}

func (x *Column) GetFlex() int32 {
	if x != nil {
		return x.Flex
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Default       bool                   `protobuf:"varint,3,opt,name=default,proto3" json:"default,omitempty"`
	StatusLabel   string                 `protobuf:"bytes,4,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Command) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *Command) GetStatusLabel() string {
	if x != nil {
		return x.StatusLabel
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Row) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Row) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Scope         map[string]string      `protobuf:"bytes,2,rep,name=scope,proto3" json:"scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ListRequest) GetScope() map[string]string {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Command       *Command               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Row           *Row                   `protobuf:"bytes,3,opt,name=row,proto3" json:"row,omitempty"`
	Scope         map[string]string      `protobuf:"bytes,4,rep,name=scope,proto3" json:"scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ExecuteRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecuteRequest) GetRow() *Row {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *ExecuteRequest) GetScope() map[string]string {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *Details               `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	Navigate      *Navigate              `protobuf:"bytes,2,opt,name=navigate,proto3" json:"navigate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *Result) GetDetails() *Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Result) GetNavigate() *Navigate {
	if x != nil {
		return x.Navigate
	}
	return nil
}

type Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Details) Reset() {
	*x = Details{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Details) ProtoMessage() {}

func (x *Details) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Details.ProtoReflect.Descriptor instead.
func (*Details) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *Details) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Details) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type Navigate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Scope         map[string]string      `protobuf:"bytes,5,rep,name=scope,proto3" json:"scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Navigate) Reset() {
	*x = Navigate{}
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Navigate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Navigate) ProtoMessage() {}

func (x *Navigate) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsdk_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Navigate.ProtoReflect.Descriptor instead.
func (*Navigate) Descriptor() ([]byte, []int) {
	return file_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *Navigate) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Navigate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Navigate) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Navigate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Navigate) GetScope() map[string]string {
	if x != nil {
		return x.Scope
	}
	return nil
}

var File_pluginsdk_proto_plugin_proto protoreflect.FileDescriptor

const file_pluginsdk_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cpluginsdk/proto/plugin.proto\x12\ro7k.plugin.v1\"\a\n" +
	"\x05Empty\"9\n" +
	"\x11InitializeRequest\x12$\n" +
	"\x0ehost_broker_id\x18\x01 \x01(\rR\fhostBrokerId\"`\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"x\n" +
	"\aContext\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x14\n" +
	"\x05cloud\x18\x02 \x01(\tR\x05cloud\x12\x1f\n" +
	"\vclouds_path\x18\x03 \x01(\tR\n" +
	"cloudsPath\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\"B\n" +
	"\tResources\x125\n" +
	"\tresources\x18\x01 \x03(\v2\x17.o7k.plugin.v1.ResourceR\tresources\"\xcd\x01\n" +
	"\bResource\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\x12/\n" +
	"\acolumns\x18\x05 \x03(\v2\x15.o7k.plugin.v1.ColumnR\acolumns\x122\n" +
	"\bcommands\x18\x06 \x03(\v2\x16.o7k.plugin.v1.CommandR\bcommands\"a\n" +
	"\x06Column\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tmin_width\x18\x03 \x01(\x05R\bminWidth\x12\x12\n" +
	"\x04flex\x18\x04 \x01(\x05R\x04flex\"z\n" +
	"\aCommand\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\adefault\x18\x03 \x01(\bR\adefault\x12!\n" +
	"\fstatus_label\x18\x04 \x01(\tR\vstatusLabel\"\x88\x01\n" +
	"\x03Row\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x06fields\x18\x02 \x03(\v2\x1e.o7k.plugin.v1.Row.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\vListRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12;\n" +
	"\x05scope\x18\x02 \x03(\v2%.o7k.plugin.v1.ListRequest.ScopeEntryR\x05scope\x1a8\n" +
	"\n" +
	"ScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\fListResponse\x12&\n" +
	"\x04rows\x18\x01 \x03(\v2\x12.o7k.plugin.v1.RowR\x04rows\"\xfe\x01\n" +
	"\x0eExecuteRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x120\n" +
	"\acommand\x18\x02 \x01(\v2\x16.o7k.plugin.v1.CommandR\acommand\x12$\n" +
	"\x03row\x18\x03 \x01(\v2\x12.o7k.plugin.v1.RowR\x03row\x12>\n" +
	"\x05scope\x18\x04 \x03(\v2(.o7k.plugin.v1.ExecuteRequest.ScopeEntryR\x05scope\x1a8\n" +
	"\n" +
	"ScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x0fExecuteResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.o7k.plugin.v1.ResultR\x06result\"o\n" +
	"\x06Result\x120\n" +
	"\adetails\x18\x01 \x01(\v2\x16.o7k.plugin.v1.DetailsR\adetails\x123\n" +
	"\bnavigate\x18\x02 \x01(\v2\x17.o7k.plugin.v1.NavigateR\bnavigate\"3\n" +
	"\aDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xd6\x01\n" +
	"\bNavigate\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x128\n" +
	"\x05scope\x18\x05 \x03(\v2\".o7k.plugin.v1.Navigate.ScopeEntryR\x05scope\x1a8\n" +
	"\n" +
	"ScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd7\x02\n" +
	"\x06Plugin\x12D\n" +
	"\n" +
	"Initialize\x12 .o7k.plugin.v1.InitializeRequest\x1a\x14.o7k.plugin.v1.Empty\x12<\n" +
	"\vGetMetadata\x12\x14.o7k.plugin.v1.Empty\x1a\x17.o7k.plugin.v1.Metadata\x12>\n" +
	"\fGetResources\x12\x14.o7k.plugin.v1.Empty\x1a\x18.o7k.plugin.v1.Resources\x12?\n" +
	"\x04List\x12\x1a.o7k.plugin.v1.ListRequest\x1a\x1b.o7k.plugin.v1.ListResponse\x12H\n" +
	"\aExecute\x12\x1d.o7k.plugin.v1.ExecuteRequest\x1a\x1e.o7k.plugin.v1.ExecuteResponse2B\n" +
	"\x04Host\x12:\n" +
	"\n" +
	"GetContext\x12\x14.o7k.plugin.v1.Empty\x1a\x16.o7k.plugin.v1.ContextB/Z-github.com/akyriako/o7k/pluginsdk/proto;protob\x06proto3"

var (
	file_pluginsdk_proto_plugin_proto_rawDescOnce sync.Once
	file_pluginsdk_proto_plugin_proto_rawDescData []byte
)

func file_pluginsdk_proto_plugin_proto_rawDescGZIP() []byte {
	file_pluginsdk_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pluginsdk_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginsdk_proto_plugin_proto_rawDesc), len(file_pluginsdk_proto_plugin_proto_rawDesc)))
	})
	return file_pluginsdk_proto_plugin_proto_rawDescData
}

var file_pluginsdk_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pluginsdk_proto_plugin_proto_goTypes = []any{
	(*Empty)(nil),             // 0: o7k.plugin.v1.Empty
	(*InitializeRequest)(nil), // 1: o7k.plugin.v1.InitializeRequest
	(*Metadata)(nil),          // 2: o7k.plugin.v1.Metadata
	(*Context)(nil),           // 3: o7k.plugin.v1.Context
	(*Resources)(nil),         // 4: o7k.plugin.v1.Resources
	(*Resource)(nil),          // 5: o7k.plugin.v1.Resource
	(*Column)(nil),            // 6: o7k.plugin.v1.Column
	(*Command)(nil),           // 7: o7k.plugin.v1.Command
	(*Row)(nil),               // 8: o7k.plugin.v1.Row
	(*ListRequest)(nil),       // 9: o7k.plugin.v1.ListRequest
	(*ListResponse)(nil),      // 10: o7k.plugin.v1.ListResponse
	(*ExecuteRequest)(nil),    // 11: o7k.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),   // 12: o7k.plugin.v1.ExecuteResponse
	(*Result)(nil),            // 13: o7k.plugin.v1.Result
	(*Details)(nil),           // 14: o7k.plugin.v1.Details
	(*Navigate)(nil),          // 15: o7k.plugin.v1.Navigate
	nil,                       // 16: o7k.plugin.v1.Row.FieldsEntry
	nil,                       // 17: o7k.plugin.v1.ListRequest.ScopeEntry
	nil,                       // 18: o7k.plugin.v1.ExecuteRequest.ScopeEntry
	nil,                       // 19: o7k.plugin.v1.Navigate.ScopeEntry
}
var file_pluginsdk_proto_plugin_proto_depIdxs = []int32{
	5,  // 0: o7k.plugin.v1.Resources.resources:type_name -> o7k.plugin.v1.Resource
	6,  // 1: o7k.plugin.v1.Resource.columns:type_name -> o7k.plugin.v1.Column
	7,  // 2: o7k.plugin.v1.Resource.commands:type_name -> o7k.plugin.v1.Command
	16, // 3: o7k.plugin.v1.Row.fields:type_name -> o7k.plugin.v1.Row.FieldsEntry
	17, // 4: o7k.plugin.v1.ListRequest.scope:type_name -> o7k.plugin.v1.ListRequest.ScopeEntry
	8,  // 5: o7k.plugin.v1.ListResponse.rows:type_name -> o7k.plugin.v1.Row
	7,  // 6: o7k.plugin.v1.ExecuteRequest.command:type_name -> o7k.plugin.v1.Command
	8,  // 7: o7k.plugin.v1.ExecuteRequest.row:type_name -> o7k.plugin.v1.Row
	18, // 8: o7k.plugin.v1.ExecuteRequest.scope:type_name -> o7k.plugin.v1.ExecuteRequest.ScopeEntry
	13, // 9: o7k.plugin.v1.ExecuteResponse.result:type_name -> o7k.plugin.v1.Result
	14, // 10: o7k.plugin.v1.Result.details:type_name -> o7k.plugin.v1.Details
	15, // 11: o7k.plugin.v1.Result.navigate:type_name -> o7k.plugin.v1.Navigate
	19, // 12: o7k.plugin.v1.Navigate.scope:type_name -> o7k.plugin.v1.Navigate.ScopeEntry
	1,  // 13: o7k.plugin.v1.Plugin.Initialize:input_type -> o7k.plugin.v1.InitializeRequest
	0,  // 14: o7k.plugin.v1.Plugin.GetMetadata:input_type -> o7k.plugin.v1.Empty
	0,  // 15: o7k.plugin.v1.Plugin.GetResources:input_type -> o7k.plugin.v1.Empty
	9,  // 16: o7k.plugin.v1.Plugin.List:input_type -> o7k.plugin.v1.ListRequest
	11, // 17: o7k.plugin.v1.Plugin.Execute:input_type -> o7k.plugin.v1.ExecuteRequest
	0,  // 18: o7k.plugin.v1.Host.GetContext:input_type -> o7k.plugin.v1.Empty
	0,  // 19: o7k.plugin.v1.Plugin.Initialize:output_type -> o7k.plugin.v1.Empty
	2,  // 20: o7k.plugin.v1.Plugin.GetMetadata:output_type -> o7k.plugin.v1.Metadata
	4,  // 21: o7k.plugin.v1.Plugin.GetResources:output_type -> o7k.plugin.v1.Resources
	10, // 22: o7k.plugin.v1.Plugin.List:output_type -> o7k.plugin.v1.ListResponse
	12, // 23: o7k.plugin.v1.Plugin.Execute:output_type -> o7k.plugin.v1.ExecuteResponse
	3,  // 24: o7k.plugin.v1.Host.GetContext:output_type -> o7k.plugin.v1.Context
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pluginsdk_proto_plugin_proto_init() }
func file_pluginsdk_proto_plugin_proto_init() {
	if File_pluginsdk_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginsdk_proto_plugin_proto_rawDesc), len(file_pluginsdk_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pluginsdk_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pluginsdk_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pluginsdk_proto_plugin_proto_msgTypes,
	}.Build()
	File_pluginsdk_proto_plugin_proto = out.File
	file_pluginsdk_proto_plugin_proto_goTypes = nil
	file_pluginsdk_proto_plugin_proto_depIdxs = nil
}
