Output assets/demo/demo.gif

Set FontSize 16
Set Width 1600
Set Height 800
Set TypingSpeed 200ms

Type "o7k"
Enter
Sleep 2s
Enter
Sleep 2s

Type ":stacks"
Enter
Down
Down
Enter
PageDown
Sleep 1s
PageDown
Sleep 1s
PageDown
Sleep 1s
Escape
Sleep 2s

Type "E"
Down
Down
Down
Down
Down
Down
Down
Down
Sleep 5s
Escape

Sleep 2s

Type "R"
Down
Down
Down
Down
Sleep 5s
Escape

Type ":load"
Tab
Enter
Sleep 3s

Type "P"
Sleep 3s

Type "M"
Sleep 3s

Type ":servers"
Enter
Sleep 3s

Type "s"
Sleep 2s
PageDown
Sleep 2s
PageDown
Sleep 3s
Escape
Sleep 3s

Type ":ali"
Tab
Enter
Sleep 3s

Type ":con"
Tab
Enter
Sleep 2s
Down
Sleep 1s
Enter
Sleep 2s

Type ":services"
Enter
Sleep 5s


# demo sequence...